#version 430 compatibility
#extension GL_ARB_compute_shader: enable
#extension GL_ARB_shader_storage_buffer_object: enable

layout(std140, binding=1) buffer bufIn
{
    vec4 inVerts[];
};

layout(std140, binding=2) buffer bufOut
{
    vec4 outVerts[];
};

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint n = gl_GlobalInvocationID.x;
    
    for(int i = 0; i < n; i++)
    {
        outVerts[i] = inVerts[i];
    }
}
